#!/bin/sh
echo :: setting up ytools environment
YPATH=~/.ytools

. $YPATH/startup.common
case "$OSTYPE" in
  darwin*)  . $YPATH/startup.osx ;;
  linux*)   . $YPATH/startup.linux ;;
  *)        echo "::: Unknown platform" ;;
esac
